name: MN8ER
favicon: null
layout_spectrum: 0.11681157047860324
typography_spectrum: 0.19688985357061028
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8534552215132862
  lightness: 0.8404177834745497
  saturation: 0.7968985887710005
  rhythmicContrast: 0.16257069539278746
purpose: []
